python inject_failures.py 1 $1
python inject_failures.py 2 $1
python inject_failures.py 3 $1
python inject_failures.py 4 $1
python inject_failures.py 5 $1
python inject_failures.py 6 $1
python inject_failures.py 7 $1
python inject_failures.py 8 $1
python inject_failures.py 9 $1
python inject_failures.py 10 $1
python inject_failures.py 11 $1
python inject_failures.py 12 $1